services:
  postgres-db:
    container_name: todothat_postgres
    image: postgres:16.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todothat_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       RAILS_ENV: development
  #   container_name: todothat_web
  #   command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
  #   volumes:
  #     - .:/rails:cached
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     postgres-db:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres-db:5432/todothat_development
  #     RAILS_ENV: development
  #     NODE_ENV: development
  #     PORT: 3000
  #     GOOGLE_CLIENT_ID: your-google-client-id
  #     GOOGLE_CLIENT_SECRET: your-google-client-secret
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3000"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
volumes:
  postgres_data: