services:
  postgres-db:
    container_name: todothat_postgres
    image: postgres:16.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todothat_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      args:
        RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-db:5432/todothat_development
      RAILS_ENV: development
      PORT: 3000
volumes:
  postgres_data: